---
title: "Logo-Sequence Generator for RNA-Immunoprecipitation followd by sequencing"
author:
  affiliation: Interdisciplinary Center for Clinical Research - RWTH-Aachen
  name: Ali T. Abdallah
  fontsize: 15pt
date: "30.11.2020"
output: 
  html_notebook:
  highlight: kate
  theme: yeti
---

<style>
.main-container{
  min-width: 1400px;!important
  margin-left: auto;!important
  margin-right: auto;!important
  font-size: 15px;!important
}
.tabset{
  font-size: 15px;!important
}
.download{
	padding: 10px 15px;
	background: #4479BA;
	color: #FFF;
	-webkit-border-radius: 4px;
	-moz-border-radius: 4px;
	border-radius: 4px;
	border: solid 1px #20538D;
	text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.4);
	-webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.4), 0 1px 1px rgba(0, 0, 0, 0.2);
	-moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.4), 0 1px 1px rgba(0, 0, 0, 0.2);
	box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.4), 0 1px 1px rgba(0, 0, 0, 0.2);
	-webkit-transition-duration: 0.2s;
	-moz-transition-duration: 0.2s;
	transition-duration: 0.2s;
	-webkit-user-select:none;
	-moz-user-select:none;
	-ms-user-select:none;
	user-select:none;
}
.download:hover{
	background: #356094;
	border: solid 1px #2A4E77;
	text-decoration: none;
}
.download:active{
	-webkit-box-shadow: inset 0 1px 4px rgba(0, 0, 0, 0.6);
	-moz-box-shadow: inset 0 1px 4px rgba(0, 0, 0, 0.6);
	box-shadow: inset 0 1px 4px rgba(0, 0, 0, 0.6);
	background: #2E5481;
	border: solid 1px #203E5F;
}

#toc_container {
    background: #f9f9f9 none repeat scroll 0 0;
    border: 0px solid #aaa;
    display: table;
    font-size: 100%;
    margin-bottom: 1em;
    padding: 10px;
    width: auto;
}

.toc_title {
    font-weight: 700;
    text-align: left;
}

#toc_container li, #toc_container ol, #toc_container ol li{
    list-style: outside none none !important;
}
</style>


```{r echo=F}
library(biomaRt)





```


